package com.intel.ebsqa.draco.enums;

public enum Menu {
	HOME, LEADS, ACCOUNTS, CONTACTS, OPPURTUNITIES, OPPURTUNITY_SEARCH, SALES_SUPPORT, DASHBOARD, REPORTS, COMMISSIONS,
	ASK_A_QUESTION, NEWSFEED, CHANNEL_SALES_ANALYSIS
}
