package com.intel.ebsqa.draco.enums;

public enum PFRActivityCategoryOptions {
	NONE, BROADCAST, DIGITAL_MEDIA, EVENT, LEAD_MANAGEMENT, OUT_OF_HOME_MEDIA, PAID_SOCIAL_MEDIA, PRINT_MEDIA,
	SEARCH_ENGINE_MARKETING
}
